[package]
name = "cli-util"
version = "0.1.0"
description = "cli support lib"
repository = "https://github.com/arlac77/rust-cli-util"
readme = "README.md"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
termion = "1.5.5"
